/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'object-detection.release+Alif-E7-M55-HP' 
 * Target:  'release+Alif-E7-M55-HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HP.h"

/* AlifSemiconductor::BSP:External peripherals:CAMERA Sensor ARX3A0@1.3.0 */
#define RTE_Drivers_CAMERA_SENSOR_ARX3A0   1           /* Driver CAMERA Sensor */
/* AlifSemiconductor::BSP:External peripherals:ILI9806E LCD panel@1.3.0 */
#define RTE_Drivers_MIPI_DSI_ILI9806E_PANEL 1   /* Driver ILI9806E LCD panel*/
/* AlifSemiconductor::BSP:External peripherals:OSPI Flash ISSI@1.3.0 */
#define RTE_Drivers_ISSI_FLASH 1
/* AlifSemiconductor::Device:SOC Peripherals:CDC@1.3.0 */
#define RTE_Drivers_CDC200 1   /* Driver CDC200*/
/* AlifSemiconductor::Device:SOC Peripherals:CPI@1.3.0 */
#define RTE_Drivers_CPI   1           /* Driver CAMERA Controller */
/* AlifSemiconductor::Device:SOC Peripherals:DMA@1.3.0 */
#define RTE_Drivers_DMA 1   /* Driver DMA*/
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:I2C@1.3.0 */
#define RTE_Drivers_I2C   1           /* Driver I2C */
/* AlifSemiconductor::Device:SOC Peripherals:I3C@1.3.0 */
#define RTE_Drivers_I3C0   1           /* Driver I3C */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI CSI2@1.3.0 */
#define RTE_Drivers_MIPI_CSI2   1   /* Driver MIPI CSI2 */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI CSI2 DPHY@1.3.0 */
#define RTE_Drivers_MIPI_DSI_CSI2_DPHY   1   /* Driver DPHY */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI@1.3.0 */
#define RTE_Drivers_MIPI_DSI   1   /* Driver MIPI DSI */
/* AlifSemiconductor::Device:SOC Peripherals:OSPI@1.3.0 */
#define RTE_Drivers_OSPI   1           /* Driver OSPI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:USART@1.3.0 */
#define RTE_Drivers_USART0   1           /* Driver UART0 */
#define RTE_Drivers_USART1   1           /* Driver UART1 */
#define RTE_Drivers_USART2   1           /* Driver UART2 */
#define RTE_Drivers_USART3   1           /* Driver UART3 */
#define RTE_Drivers_USART4   1           /* Driver UART4 */
#define RTE_Drivers_USART5   1           /* Driver UART5 */
#define RTE_Drivers_USART6   1           /* Driver UART6 */
#define RTE_Drivers_USART7   1           /* Driver UART7 */
/* Arm::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.23.2 */
#define RTE_ETHOS_U_CORE_DRIVER
/* tensorflow::Data Exchange:Serialization:flatbuffers&tensorflow@1.22.8 */
#define RTE_DataExchange_Serialization_flatbuffers     /* flatbuffers */
/* tensorflow::Data Processing:Math:gemmlowp fixed-point&tensorflow@1.22.8 */
#define RTE_DataExchange_Math_gemmlowp     /* gemmlowp */
/* tensorflow::Data Processing:Math:kissfft&tensorflow@1.22.8 */
#define RTE_DataExchange_Math_kissfft     /* kissfft */
/* tensorflow::Data Processing:Math:ruy&tensorflow@1.22.8 */
#define RTE_DataProcessing_Math_ruy     /* ruy */
/* tensorflow::Machine Learning:TensorFlow:Kernel&Ethos-U@1.22.8 */
#define RTE_ML_TF_LITE     /* TF */
/* tensorflow::Machine Learning:TensorFlow:Testing@1.22.8 */
#define RTE_ML_TF_LITE     /* TF */


#endif /* RTE_COMPONENTS_H */
